config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   resources :videos

end

app/models/video.rb
class Video < ActiveRecord::Base
  def thumbnail
    return url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def valid_url(url)
    @default_value = nil
    @match = /^(?:https?\:\/\/)?(?:www\.)?youtube\.com\/(?:[^?]+)\?(.+)$/.match(url)
    if @match then
      @query = @match.captures[0]
      @id_start_index = @query.index 'v='
      if @id_start_index.nil? then
        return @default_value
      end
      @id_start_index += 2
      @id_end_index = @query.index '&', @id_start_index
      if @id_end_index.nil? then
        @id_end_index = @query.length
      end
      return @query[@id_start_index,@id_end_index-@id_start_index]
    else
      @match = /^(?:https?\:\/\/)?(?:www\.)?youtu\.be\/([^?]+)(?:.+)$/.match(url)
      if @match then
        return @match.captures[0]
      else
        return @default_value
      end
    end
  end

  def index
    @title = "All Videos"
    @vidyas = Video.all
  end

  def show
    @vidyas = Video.order("view_count desc").limit(5)
    @vidya = Video.find(params[:id])
    @vidya.update_attributes "view_count"=> (@vidya.view_count + 1)
  end

  def new
    if params.has_key?(:error)
      @errorzy = params[:error].html_safe
      params.delete :error
    end
  end

  def create
    @URL = valid_url params[:video_data][:url]
    print(@URL)
    if not @URL then
      redirect_to :controller=>"videos", :action => "new", :error=>"Sorry, but <strong>" + params[:video_data][:url] + "</strong> is not a valid Youtube URL."
    else
      if params[:video_data][:name].length < 1 then
        redirect_to :controller=>"videos", action=> "new", :error=>"Names cannot be empty!"
      end
      @vidya = Video.new :name=>params[:video_data][:name], url:@URL
      @vidya.save
      redirect_to @vidya
    end
  end

  def destroy
    @vidya = Video.find(params[:id])
    @vidya.destroy
    redirect_to videos_path
  end

  def edit
    @vidya = Video.find(params[:id])
    if params.has_key?(:error)
      @errorzy = params[:error].html_safe
      params.delete :error
    end
  end

  def update
    @URL = valid_url params[:video_data][:url]
    if not @URL then
      redirect_to :controller=>"videos", :action => "edit", :error=>"Sorry, but <strong>" + params[:video_data][:url] + "</strong> is not a valid Youtube URL."
    else
      if params[:video_data][:name].length < 1 then
        redirect_to :controller=>"videos", :action=> "edit", :error=>"Names cannot be empty!"
      else
        @vidya = Video.find(params[:id])
        @vidya.update_attributes "name"=>params[:video_data][:name],"url"=>@URL
        redirect_to @vidya
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @vidyas = Video.order("created_at desc").limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if not defined?(@title) then %>
    Ozark Web Theatre
    <% else %>
    <%= @title %>
    <% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation">
            <a href="/">Home</a>
          </li>
          <li role="presentation">
            <a href="/videos">Videos</a>
          </li>
          <li role="presentation">
            <a href="/videos/new">Add A Video</a>
          </li>
        </ul>
      </nav>
      <h3 class="text-muted">Ozark Web Theatre</h3>
    </div>
    <%= yield %>
    <footer class="footer navbar navbar-default navbar-fixed-bottom">
      <div class="container">
        <span class="navbar-text">Ozark Web Developers, LLC 2015</span>
      </div>
    </footer>
  </div>
</body>
</html>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<% if not defined?(@errorzy).nil? then %>
  <div class="alert alert-danger">
    <%= @errorzy %>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Youtube Video - <%= @vidya.name %></h3>
  </div>
  <div class="panel-body">
    <%= form_for :video_data, url: video_path(@vidya), method: :patch do |f| %>
      <div class="form-group">
        <label for="videoName">Video Name</label>
        <%= f.text_field "name", "class" => "form-control", "id" => "videoName", "placeholder" => "Video Name", "value" =>@vidya.name %>
      </div>
      <div class="form-group">
        <label for="videoName">Video URL</label>
        <%= f.text_field "url", "class" => "form-control", "id" => "videoLink", "placeholder" => "Video URL", "value" => "https://youtube.com/watch?v=" + @vidya.url %>
      </div>
      <%= f.submit "class"=>"btn btn-success","value"=>"Save" %>
    <% end %>
  </div>
</div>

app/views/videos/index.html.erb
<h3>All Videos</h3>
<ul class="video_list list-unstyled list-inline">
  <% @vidyas.each do |f| %>
    <li class="">
      <a href="<%= video_path(f,action:"show") %>">
        <img
          class="media"
          src="http://img.youtube.com/vi/<%= f.url %>/default.jpg"
          alt="<%= f.name %>"
          title="<%= f.name %>"/><br/>
        <strong><%= f.name %></strong>
      </a>
    </li>
  <%end %>
</ul>

app/views/videos/new.html.erb
<h1>New Video</h1>

<% if not defined?(@errorzy).nil? then %>
  <div class="alert alert-danger">
    <%= @errorzy %>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Youtube Video</h3>
  </div>
  <div class="panel-body">
    <%= form_for :video_data, url: videos_path do |f| %>
      <div class="form-group">
        <label for="videoName">Video Name</label>
        <%= f.text_field "name", "class" => "form-control", "id" => "videoName", "placeholder" => "Video Name" %>
      </div>
      <div class="form-group">
        <label for="videoName">Video URL</label>
        <%= f.text_field "url", "class" => "form-control", "id" => "videoLink", "placeholder" => "Video URL" %>
      </div>
      <%= f.submit "class"=>"btn btn-success","value"=>"Save" %>
    <% end %>
  </div>
</div>

app/views/videos/show.html.erb
<h1 class="col-md-12"><%= @vidya.name %></h1>

<div class="col-md-12">
  <div class="embed-responsive embed-responsive-16by9">
    <iframe width="560" height="315" src="//www.youtube.com/embed/<%= @vidya.url %>" allowfullscreen=""></iframe>
  </div>
</div>

<div class="col-md-12 video_view_meta">
  <span>
    <strong>Views: <%= @vidya.view_count %></strong>
  </span>
  <span>
    <%= link_to 'Edit', edit_video_path(@vidya) %>
  </span>
  <span>
    <%= link_to 'Delete', video_path(@vidya), method: :delete %>
  </span>
</div>

<h4>More Videos</h4>

<ul class="video_list list-unstyled list-inline">
  <% @vidyas.each do |f| %>
    <li class="">
      <a href="<%= video_path(f,action:"show") %>">
        <img
          class="media"
          src="http://img.youtube.com/vi/<%= f.url %>/default.jpg"
          alt="<%= f.name %>"
          title="<%= f.name %>"/><br/>
        <strong><%= f.name %></strong>
      </a>
    </li>
  <%end %>
</ul>

<a href="<%= videos_path %>" class="btn btn-primary">All videos</a>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>The Most Localist Theatre</h1>
  <p class="lead">Collaboratively mash a pot of youtube videos to make magic.</p>
  <p>
    <a class="btn btn-lg btn-success" href="<%= videos_path action:"index" %>">Submit A Video!</a>
  </p>
</div>

<h4>Latest Videos</h4>

<ul class="video_list list-unstyled list-inline">
  <% @vidyas.each do |f| %>
    <li class="">
      <a href="<%= video_path(f,action:"show") %>">
        <img
          class="media"
          src="http://img.youtube.com/vi/<%= f.url %>/default.jpg"
          alt="<%= f.name %>"
          title="<%= f.name %>"/><br/>
        <strong><%= f.name %></strong>
      </a>
    </li>
  <%end %>
</ul>

<a href="<%= videos_path %>" class="btn btn-primary">Find more videos</a>